EasyLearn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from users import views as users_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', users_views.home_page, name='home'),  # TODO: move home view to main app
    path('register/', users_views.RegisterFormWizard.as_view(), name='register-wizard'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('user/', include(('users.urls', 'users'), namespace='users')),
    path('post/', include(('posts.urls', 'posts'), namespace='posts')),
    path('file/', include(('files.urls', 'files'), namespace='files')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from chat.views import *

urlpatterns = [
    url(r'^$', RedirectView.as_view(permanent=True, url='inbox/'), name='messages_redirect'),
    url(r'^inbox/$', inbox, name='messages_inbox'),
    url(r'^outbox/$', outbox, name='messages_outbox'),
    url(r'^compose/$', compose, name='messages_compose'),
    url(r'^admin_message/$', compose_admin_message, name='messages_admin_compose'),
    #url(r'^compose/(?P<id>[\d]+)/$', compose, name='messages_compose'),
    url(r'^compose/(?P<recipient>[\w.@+-]+)/$', compose, name='messages_compose_to'),
    url(r'^reply/(?P<message_id>[\d]+)/$', reply, name='messages_reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', view, name='messages_detail'),
    url(r'^delete_inbox/(?P<message_id>[\d]+)/$', delete_inbox, name='message_delete_inbox'),
    url(r'^delete_outbox/(?P<message_id>[\d]+)/$', delete_outbox, name='message_delete_outbox'),
    #url(r'^undelete/(?P<message_id>[\d]+)/$', undelete, name='messages_undelete'),
    #url(r'^trash/$', trash, name='messages_trash'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class MessageManager(models.Manager):

    def inbox_for(self, user):
        """
        Returns all messages that were received by the given user and are not
        marked as deleted.
        """
        return self.filter(
            recipient=user,
            recipient_deleted_at__isnull=True,
        )

    def outbox_for(self, user):
        """
        Returns all messages that were sent by the given user and are not
        marked as deleted.
        """
        return self.filter(
            sender=user,
            sender_deleted_at__isnull=True,
        )

    def trash_for(self, user):
        """
        Returns all messages that were either received or sent by the given
        user and are marked as deleted.
        """
        return self.filter(
            recipient=user,
            recipient_deleted_at__isnull=False,
        ) | self.filter(
            sender=user,
            sender_deleted_at__isnull=False,
        )


class Message(models.Model):
    """
    A private message from user to user
    """
    subject = models.CharField(max_length=50)
    body = models.TextField(max_length=1500)
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    recipient = models.ForeignKey(User, related_name='received_messages', on_delete=models.CASCADE)
    parent_msg = models.ForeignKey('self', related_name='next_messages', null=True, blank=True, on_delete=models.CASCADE)
    sent_at = models.DateTimeField(auto_now_add=True)
    read_at = models.DateTimeField(null=True, blank=True)
    replied_at = models.DateTimeField(null=True, blank=True)
    sender_deleted_at = models.DateTimeField(null=True, blank=True)
    recipient_deleted_at = models.DateTimeField(null=True, blank=True)

    objects = MessageManager()

    def new(self):
        """returns whether the recipient has read the message or not"""
        if self.read_at is not None:
            return False
        return True

    def replied(self):
        """returns whether the recipient has written a reply to this message"""
        if self.replied_at is not None:
            return True
        return False

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse('messages_detail', args=(self.id,))

    def save(self, **kwargs):
        if not self.id:
            self.sent_at = timezone.now()
        super(Message, self).save(**kwargs)

    class Meta:
        ordering = ['-sent_at']


def inbox_count_for(user):
    """
    returns the number of unread messages for the given user but does not
    mark them seen
    """
    return Message.objects.filter(recipient=user, read_at__isnull=True, recipient_deleted_at__isnull=True).count()

chat/views.py
from django.contrib.auth.decorators import login_required
from chat.models import Message
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponseRedirect
from django.utils import timezone
from chat.forms import ComposeForm, ComposeAdminForm, get_user_model, get_username_field
from django.utils.translation import ugettext, ugettext_lazy as _
from django.utils.text import wrap
from django.contrib import messages
from django.urls import reverse

User = get_user_model()


def format_quote(sender, body):
    """
    Wraps text at 55 chars and prepends each
    line with `> `.
    Used for quoting messages in replies.
    """
    lines = wrap(body, 55).split('\n')
    for i, line in enumerate(lines):
        lines[i] = "> %s" % line
    quote = '\n'.join(lines)
    return ugettext(u"%(sender)s wrote:\n%(body)s") % {
        'sender': sender,
        'body': quote
    }


@login_required
def inbox(request, template_name='chat/inbox.html'):
    """
    Displays a list of received messages for the current user.
    Optional Arguments:
        ``template_name``: name of the template to use.
    """
    message_list = Message.objects.inbox_for(request.user)
    is_staff = request.user.is_staff
    return render(request, template_name, {
        'message_list': message_list,
        'is_staff': is_staff,
    })


@login_required
def outbox(request, template_name='chat/outbox.html'):
    """
    Displays a list of sent messages by the current user.
    Optional arguments:
        ``template_name``: name of the template to use.
    """
    message_list = Message.objects.outbox_for(request.user)
    is_staff = request.user.is_staff
    return render(request, template_name, {
        'message_list': message_list,
        'is_staff': is_staff,
    })


@login_required
def view(request, message_id, form_class=ComposeForm, quote_helper=format_quote,
         subject_template=_(u"Re: %(subject)s"),
         template_name='chat/view.html'):
    """
    Shows a single message.``message_id`` argument is required.
    The user is only allowed to see the message, if he is either
    the sender or the recipient. If the user is not allowed a 404
    is raised.
    If the user is the recipient and the message is unread
    ``read_at`` is set to the current datetime.
    If the user is the recipient a reply form will be added to the
    tenplate context, otherwise 'reply_form' will be None.
    """
    user = request.user
    now = timezone.now()
    message = get_object_or_404(Message, id=message_id)
    if (message.sender != user) and (message.recipient != user):
        raise Http404
    if message.read_at is None and message.recipient == user:
        message.read_at = now
        message.save()
    is_staff = request.user.is_staff
    from_inbox = False
    if request.user == message.recipient:
        from_inbox = True
    context = {'message': message, 'reply_form': None, 'is_staff': is_staff, 'from_inbox': from_inbox}
    #if message.recipient == user:
        #form = form_class(initial={
            #'body': quote_helper(message.sender, message.body),
            #'subject': subject_template % {'subject': message.subject},
            #'recipient': [message.sender,]
            #})
        #context['reply_form'] = form

    return render(request, template_name, context)


@login_required
def reply(request, message_id, form_class=ComposeForm,
          template_name='chat/compose.html', success_url=None,
          recipient_filter=None, quote_helper=format_quote,
          subject_template=_(u"Re: %(subject)s"),):
    """
    Prepares the ``form_class`` form for writing a reply to a given message
    (specified via ``message_id``). Uses the ``format_quote`` helper from
    ``messages.utils`` to pre-format the quote. To change the quote format
    assign a different ``quote_helper`` kwarg in your url-conf.
    """
    parent = get_object_or_404(Message, id=message_id)

    if parent.sender != request.user and parent.recipient != request.user:
        raise Http404

    if request.method == "POST":
        sender = request.user
        form = form_class(request.POST, recipient_filter=recipient_filter)
        #form = form_class(request.POST, recipient_filter=recipient_filter)
        if form.is_valid():
            form.save(sender=sender, parent_msg=parent)
            messages.info(request, _(u"Message successfully sent."))
            if success_url is None:
                success_url = reverse('chat:messages_inbox')
            return HttpResponseRedirect(success_url)
    else:
        form = form_class(initial={
            'body': quote_helper(parent.sender, parent.body),
            'subject': subject_template % {'subject': parent.subject},
            'recipient': [parent.sender,]
            })
    return render(request, template_name, {
        'form': form,
    })


@login_required
def compose(request, recipient=None, form_class=ComposeForm,
            template_name='chat/compose.html', success_url=None,
            recipient_filter=None):
    """
    Displays and handles the ``form_class`` form to compose new messages.
    Required Arguments: None
    Optional Arguments:
        ``recipient``: username of a `django.contrib.auth` User, who should
                       receive the message, optionally multiple usernames
                       could be separated by a '+'
        ``form_class``: the form-class to use
        ``template_name``: the template to use
        ``success_url``: where to redirect after successfull submission
    """
    is_staff = request.user.is_staff
    friends_list = request.user.profile.friends.all()
    users_list = tuple([(friend.user, friend.user.first_name+' '+friend.user.last_name) for friend in friends_list])

    if request.method == "POST":
        sender = request.user
        form = form_class(request.POST, friends_list=users_list, recipient_filter=recipient_filter)
        if form.is_valid():
            form.save(sender=sender)
            messages.info(request, _(u"Message successfully sent."))
            if success_url is None:
                success_url = reverse('chat:messages_inbox')
            if 'next' in request.GET:
                success_url = request.GET['next']
            return HttpResponseRedirect(success_url)
    else:
        form = form_class(friends_list=users_list)
        if recipient is not None:
            recipients = [u for u in User.objects.filter(**{'%s__in' % get_username_field(): [r.strip() for r in recipient.split('+')]})]
            form.fields['recipient'].initial = recipients
    return render(request, template_name, {'form': form, 'is_staff': is_staff})

@login_required
def compose_admin_message(request, recipient=None, form_class=ComposeAdminForm,
            template_name='chat/admin_message.html', success_url=None,
            recipient_filter=None):


    users_list = list(User.objects.all())
    users_list.remove(request.user)
    is_staff = request.user.is_staff
    if request.method == "POST":
        sender = request.user
        form = form_class(request.POST, friends_list=users_list, recipient_filter=recipient_filter)
        if form.is_valid():
            form.save(sender=sender)
            messages.info(request, _(u"Message successfully sent."))
            if success_url is None:
                success_url = reverse('chat:messages_inbox')
            if 'next' in request.GET:
                success_url = request.GET['next']
            return HttpResponseRedirect(success_url)
    else:
        form = form_class(friends_list=users_list)
        if recipient is not None:
            recipients = [u for u in User.objects.filter(**{'%s__in' % get_username_field(): [r.strip() for r in recipient.split('+')]})]
            form.fields['recipient'].initial = recipients
    return render(request, template_name, {'form': form, 'is_staff': is_staff})

@login_required
def delete_inbox(request, message_id):
    message = get_object_or_404(Message, id=message_id)
    message.delete()
    return redirect('chat:messages_inbox')

@login_required
def delete_outbox(request, message_id):
    message = get_object_or_404(Message, id=message_id)
    message.delete()
    return redirect('chat:messages_outbox')

chat/templates/chat/admin_message.html
{% extends "chat/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block sidebar %}
<div class="btn-group-vertical">
    <a href="{% url 'chat:messages_inbox' %}" class="btn btn-outline-info">Inbox</a>
    <a href="{% url 'chat:messages_outbox' %}" class="btn btn-outline-info">Sent Messages</a>
    <a href="{% url 'chat:messages_compose' %}" class="btn btn-outline-info">New Message</a>
    {% if is_staff %}
    <a href="{% url 'chat:messages_admin_compose' %}" class="btn btn-outline-info">Admin Message</a>
    {% endif %}
</div>
<!--<ul class="subnavilist">
    <li><a href="{% url 'chat:messages_inbox' %} ">&raquo;&nbsp;{% trans "Inbox" %}</a></li>
    <li><a href="{% url 'chat:messages_outbox' %} ">&raquo;&nbsp;{% trans "Sent Messages" %}</a></li>
    <li><a href="{% url 'chat:messages_compose' %} ">&raquo;&nbsp;{% trans "New Message" %}</a></li>
    {% if is_staff %}
    <li><a href="{% url 'chat:messages_admin_compose' %} ">&raquo;&nbsp;{% trans "Admin Message" %}</a></li>
    {% endif %}
</ul>-->
{% endblock %}

{% block content %}
<h1>{% trans "Compose Admin Message"%}</h1>
<form action="" method="post">
{% csrf_token %}
<table>
    {{ form|crispy }}
</table>
<br><button class="btn btn-outline-info" type="submit">Send</button>
</form>

{% endblock %}

chat/templates/chat/base.html
{% extends "posts/base.html" %}
{% load i18n %}

{% block content %}
{% endblock %}
{% block sidebar %}
<ul class="subnavilist">
    <li><a href="{% url 'messages_inbox' %} ">&raquo;&nbsp;{% trans "Inbox" %}</a></li>
    <li><a href="{% url 'messages_outbox' %} ">&raquo;&nbsp;{% trans "Sent Messages" %}</a></li>
    <li><a href="{% url 'messages_compose' %} ">&raquo;&nbsp;{% trans "New Message" %}</a></li>
</ul>
{% endblock %}

chat/templates/chat/compose.html
{% extends "chat/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block sidebar %}
<div class="btn-group-vertical">
    <a href="{% url 'chat:messages_inbox' %}" class="btn btn-outline-info">Inbox</a>
    <a href="{% url 'chat:messages_outbox' %}" class="btn btn-outline-info">Sent Messages</a>
    <a href="{% url 'chat:messages_compose' %}" class="btn btn-outline-info">New Message</a>
    {% if is_staff %}
    <a href="{% url 'chat:messages_admin_compose' %}" class="btn btn-outline-info">Admin Message</a>
    {% endif %}
</div>
<!--<ul class="subnavilist">
    <li><a href="{% url 'chat:messages_inbox' %} ">&raquo;&nbsp;{% trans "Inbox" %}</a></li>
    <li><a href="{% url 'chat:messages_outbox' %} ">&raquo;&nbsp;{% trans "Sent Messages" %}</a></li>
    <li><a href="{% url 'chat:messages_compose' %} ">&raquo;&nbsp;{% trans "New Message" %}</a></li>
    {% if is_staff %}
    <li><a href="{% url 'chat:messages_admin_compose' %} ">&raquo;&nbsp;{% trans "Admin Message" %}</a></li>
    {% endif %}
</ul>-->
{% endblock %}

{% block content %}
<h1>{% trans "Compose Message"%}</h1>
<form action="" method="post">
{% csrf_token %}
<table>
    {{ form|crispy }}
</table>
<br><button class="btn btn-outline-info" type="submit">Send</button>
</form>

{% endblock %}

chat/templates/chat/inbox.html
{% extends "chat/base.html" %}
{% load i18n %}

{% block sidebar %}

<div class="btn-group-vertical">
    <a href="{% url 'chat:messages_inbox' %}" class="btn btn-outline-info">Inbox</a>
    <a href="{% url 'chat:messages_outbox' %}" class="btn btn-outline-info">Sent Messages</a>
    <a href="{% url 'chat:messages_compose' %}" class="btn btn-outline-info">New Message</a>
    {% if is_staff %}
    <a href="{% url 'chat:messages_admin_compose' %}" class="btn btn-outline-info">Admin Message</a>
    {% endif %}
</div>
<!--<ul class="subnavilist">
    <li><a href="{% url 'chat:messages_inbox' %} ">&raquo;&nbsp;{% trans "Inbox" %}</a></li>
    <li><a href="{% url 'chat:messages_outbox' %} ">&raquo;&nbsp;{% trans "Sent Messages" %}</a></li>
    <li><a href="{% url 'chat:messages_compose' %} ">&raquo;&nbsp;{% trans "New Message" %}</a></li>
    {% if is_staff %}
    <li><a href="{% url 'chat:messages_admin_compose' %} ">&raquo;&nbsp;{% trans "Admin Message" %}</a></li>
    {% endif %}

</ul>-->
{% endblock %}

{% block content %}
<h1>{% trans "Inbox" %}</h1>
{% if message_list %}
<table  class="table order-column hover">
    <thead>
        <tr><th>{% trans "Sender" %}</th><th>{% trans "Subject" %}</th><th>{% trans "Received" %}</th><th>{% trans "Action" %}</th></tr>
    </thead>
    <tbody>
{% for message in message_list %}
    <tr>
        <td><a href="/user/show-users/selected-user/{{ message.sender.id }}">{{message.sender.first_name}} {{message.sender.last_name}}</a></td>
        <td>
            {% if message.new %}<strong>{% endif %}
            {% if message.replied %}<em>{% endif %}
            <a href="/chat/view/{{ message.id }}">{{ message.subject }}</a>
            {% if message.replied %}</em>{% endif %}
            {% if message.new %}</strong>{% endif %}</td>
        <td>{{ message.sent_at|date:_("DATETIME_FORMAT") }}</td>
        <td><a href="{% url 'chat:message_delete_inbox' message.id %}" class="btn btn-outline-info">Delete</a></td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>{% trans "No messages." %}</p>
{% endif %}
{% endblock %}

chat/templates/chat/outbox.html
{% extends "posts/base.html" %}
{% load i18n %}

{% block sidebar %}
<div class="btn-group-vertical">
    <a href="{% url 'chat:messages_inbox' %}" class="btn btn-outline-info">Inbox</a>
    <a href="{% url 'chat:messages_outbox' %}" class="btn btn-outline-info">Sent Messages</a>
    <a href="{% url 'chat:messages_compose' %}" class="btn btn-outline-info">New Message</a>
    {% if is_staff %}
    <a href="{% url 'chat:messages_admin_compose' %}" class="btn btn-outline-info">Admin Message</a>
    {% endif %}
</div>
<!--<ul class="subnavilist">
    <li><a href="{% url 'chat:messages_inbox' %} ">&raquo;&nbsp;{% trans "Inbox" %}</a></li>
    <li><a href="{% url 'chat:messages_outbox' %} ">&raquo;&nbsp;{% trans "Sent Messages" %}</a></li>
    <li><a href="{% url 'chat:messages_compose' %} ">&raquo;&nbsp;{% trans "New Message" %}</a></li>
    {% if is_staff %}
    <li><a href="{% url 'chat:messages_admin_compose' %} ">&raquo;&nbsp;{% trans "Admin Message" %}</a></li>
    {% endif %}
</ul>-->
{% endblock %}

{% block content %}
<h1>{% trans "Sent Messages" %}</h1>
{% if message_list %}
<table  class="table order-column hover">
    <thead>
        <tr><th>{% trans "Recipient" %}</th><th>{% trans "Subject" %}</th><th>{% trans "Sent" %}</th><th>{% trans "Action" %}</th></tr>
    </thead>
    <tbody>
{% for message in message_list %}
    <tr>
        <td><a href="/user/show-users/selected-user/{{ message.recipient.id }}">{{message.recipient.first_name}} {{message.recipient.last_name}}</a></td>
        <td>
        <a href="/chat/view/{{ message.id }}">{{ message.subject }}</a>
        </td>
        <td>{{ message.sent_at|date:_("DATETIME_FORMAT") }}</td>
        <td><a href="{% url 'chat:message_delete_outbox' message.id %}" class="btn btn-outline-info">Delete</a></td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>{% trans "No messages." %}</p>
{% endif %}
{% endblock %}

chat/templates/chat/view.html
{% extends "posts/base.html" %}
{% load i18n %}

{% block sidebar %}
<div class="btn-group-vertical">
    <a href="{% url 'chat:messages_inbox' %}" class="btn btn-outline-info">Inbox</a>
    <a href="{% url 'chat:messages_outbox' %}" class="btn btn-outline-info">Sent Messages</a>
    <a href="{% url 'chat:messages_compose' %}" class="btn btn-outline-info">New Message</a>
    {% if is_staff %}
    <a href="{% url 'chat:messages_admin_compose' %}" class="btn btn-outline-info">Admin Message</a>
    {% endif %}
</div>
<!--<ul class="subnavilist">
    <li><a href="{% url 'chat:messages_inbox' %} ">&raquo;&nbsp;{% trans "Inbox" %}</a></li>
    <li><a href="{% url 'chat:messages_outbox' %} ">&raquo;&nbsp;{% trans "Sent Messages" %}</a></li>
    <li><a href="{% url 'chat:messages_compose' %} ">&raquo;&nbsp;{% trans "New Message" %}</a></li>
    {% if is_staff %}
    <li><a href="{% url 'chat:messages_admin_compose' %} ">&raquo;&nbsp;{% trans "Admin Message" %}</a></li>
    {% endif %}
</ul>-->
{% endblock %}

{% block content %}
<article class="content-section" >
          <div class="media-body">
            <div class="article-metadata">
                {% if from_inbox %}
                <a class="mr-2" >Message From:</a>
                <a class="mr-2" href="/user/show-users/selected-user/{{ message.sender.id }}">{{message.sender.first_name}} {{message.sender.last_name}}</a>
                {% else %}
                <a class="mr-2" >Message To:</a>
                <a class="mr-2" href="/user/show-users/selected-user/{{ message.recipient.id }}">{{message.recipient.first_name}} {{message.recipient.last_name}}</a>
                {% endif %}
              <small class="text-muted">{{ message.sent_at|date:"F d, Y" }}</small>
            </div>
            <div>
                <h3><a class="article-title" >{{ message.subject }}</a></h3>
                <p class="article-content">{{ message.body }}</p>
            </div>
          </div>
        </article>

<!--<h1>{% trans "View Message" %}</h1>
<dl class="message-headers">
    <dt>{% trans "Subject" %}</dt>
    <dd><strong>{{ message.subject }}</strong></dd>
    <dt>{% trans "Sender" %}</dt>
    <p><a href="/user/show-users/selected-user/{{ message.sender.id }}">{{message.sender.first_name}} {{message.sender.last_name}}</a></p>
    <dt>{% trans "Date" %} </dt>
    <dd>{{ message.sent_at|date:_("DATETIME_FORMAT")}}</dd>
</dl>
{{ message.body|linebreaksbr }}<br /><br />-->
<!--
{% ifequal message.recipient.pk user.pk %}
<a href="{% url 'chat:messages_reply' message.id %}">{% trans "Reply" %}</a>
{% endifequal %}-->


{% comment %}Example reply_form integration
{% if reply_form %}
<h1>{% trans "Compose reply"%}</h1>
<form action="{% url 'chat:messages_reply' message.id %}" method="post">
{% csrf_token %}
<table>
{{ reply_form.as_table }}
</table>
<input type="submit" value="{% trans "Send" %} &raquo;"/>
</form>
{% endif %}
{% endcomment %}
{% endblock %}