EasyLearn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from users import views as users_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', users_views.home_page, name='home'),  # TODO: move home view to main app
    path('register/', users_views.RegisterFormWizard.as_view(), name='register-wizard'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('user/', include(('users.urls', 'users'), namespace='users')),
    path('post/', include(('posts.urls', 'posts'), namespace='posts')),
    path('file/', include(('files.urls', 'files'), namespace='files')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from chat.views import *

urlpatterns = [
    url(r'^$', RedirectView.as_view(permanent=True, url='inbox/'), name='messages_redirect'),
    url(r'^inbox/$', inbox, name='messages_inbox'),
    url(r'^outbox/$', outbox, name='messages_outbox'),
    url(r'^compose/$', compose, name='messages_compose'),
    url(r'^admin_message/$', compose_admin_message, name='messages_admin_compose'),
    #url(r'^compose/(?P<id>[\d]+)/$', compose, name='messages_compose'),
    url(r'^compose/(?P<recipient>[\w.@+-]+)/$', compose, name='messages_compose_to'),
    url(r'^reply/(?P<message_id>[\d]+)/$', reply, name='messages_reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', view, name='messages_detail'),
    url(r'^delete_inbox/(?P<message_id>[\d]+)/$', delete_inbox, name='message_delete_inbox'),
    url(r'^delete_outbox/(?P<message_id>[\d]+)/$', delete_outbox, name='message_delete_outbox'),
    #url(r'^undelete/(?P<message_id>[\d]+)/$', undelete, name='messages_undelete'),
    #url(r'^trash/$', trash, name='messages_trash'),
]

files/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

urlpatterns = [
    path('show-files/', views.show_files, name='show_files'),
    path('add-file/', views.add_new_file, name='add_file'),
    path('download-file/', views.download_file, name='download_file'),
    url(r'^download-file/(?P<file_id>\d+)/$', views.download_file, name='download_file'),
    path('delete-files/', views.delete_files, name='delete_files'),
    path('delete/<int:file_id>/', login_required(views.delete_one_file), name='delete_one_file'),
]

files/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from EasyLearn import settings
from users.models import Course, Degree
import os
from django.core.exceptions import ValidationError
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.dispatch import receiver
import uuid
from django.utils.translation import ugettext_lazy as _

EXTENSIONS_WHITELIST = ('pdf', 'docx', 'doc', 'jpg', 'png', 'jpeg', 'txt', 'zip', 'rar')
UPLOAD_TO_DIR = 'files/'
MAX_FILE_SIZE = 26214400  # 25MB


class File(models.Model):

    def validate_file_size(value):
        if value.size > MAX_FILE_SIZE:
            raise ValidationError(u'Max size of uploaded file is {0} MB.'.format(MAX_FILE_SIZE / 2**20))

    file_name = models.CharField(max_length=30, null=True, blank=True)
    file_type = models.CharField(max_length=10, null=True, blank=True)
    file_url = models.FileField(upload_to=UPLOAD_TO_DIR, default='', validators=[validate_file_size])
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    create_at = models.DateField(null=True)
    upload_at = models.DateTimeField(auto_now_add=True)
    file_size = models.CharField(max_length=10, null=True, blank=True)
    category = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    related_degrees = models.ManyToManyField(Degree, blank=True)

    def __str__(self):
        return str(self.file_name)

    def get_file_extension(self):
        name, extension = os.path.splitext(self.file_url.name)
        return str(extension)[1:]  # remove the '.'

    def get_file_size(self):
        size_in_bytes = self.file_url.size
        if 0 < size_in_bytes < 1024:
            return '{0} B'.format(size_in_bytes)
        elif 1024 <= size_in_bytes < 1024**2:
            return '{0:.2f} KB'.format(size_in_bytes / 1024)
        else:
            return '{0:.2f} MB'.format(size_in_bytes / (1024**2))

    def get_str_of_related_degrees(self):
        output = ''
        for degree in self.related_degrees.all():
            output += degree.degree_name + ', '
        return output[:-2]

    def save(self, **kwargs):
        extension = self.get_file_extension()
        if extension not in EXTENSIONS_WHITELIST:
            raise ValidationError('The file extension is not allowed')
        if not self.id:
            self.create_at = timezone.now()
        self.file_size = self.get_file_size()
        super(File, self).save(**kwargs)
        initial_path = self.file_url.path
        self.file_type = self.get_file_extension()
        owner_username = str(self.owner).replace(' ', '')
        file_category = str(self.category).replace(' ', '')
        self.file_name = '' + str(self.id) + '_' + owner_username + '_' + file_category + '.' + str(self.file_type)
        new_path = settings.MEDIA_ROOT + '/' + UPLOAD_TO_DIR + self.file_name
        os.rename(initial_path, new_path)
        self.file_url.name = os.path.join(UPLOAD_TO_DIR, self.file_name)
        super(File, self).save(**kwargs)


    #@receiver(models.signals.post_delete, sender=File)
    #def auto_delete_file_on_delete(sender, instance, **kwargs):
        """
        Deletes file from filesystem
        when corresponding `MediaFile` object is deleted.
        """
        #if instance.file_url:
            #if os.path.isfile(instance.file_url.path):

                #os.remove(instance.file_url.path)

    #@receiver(pre_delete, sender=File)
    #def mymodel_delete(sender, instance, **kwargs):
        #'''Pass false so FileField doesn't save the model.'''
        #instance.file.delete(False)

    #def delete(self, using=None, keep_parents=False):
        #os.remove(self.legal_file.file_url.path)
        #super(File, self).delete(self)

files/forms.py
from django import forms
from files.models import File, EXTENSIONS_WHITELIST
from users.models import Course, Degree
from users.views import User

FIELD_NAME_MAPPING = {
    'category': 'file_type'
}


class DateInput(forms.DateInput):
    input_type = 'date'


class CreateNewFileForm(forms.ModelForm):
    file_create_at_help_text = 'Please specify the date you created the file for people to know if its relevant'

    category = forms.ModelChoiceField(queryset=Course.objects.all())
    related_degrees = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                                     queryset=Degree.objects.all(),
                                                     error_messages={'required': 'You must select at least one degree.'})
    file_create_at = forms.DateField(help_text=file_create_at_help_text, widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    def add_prefix(self, field_name):
        # look up field name; return original if not found
        field_name = FIELD_NAME_MAPPING.get(field_name, field_name)
        return super(CreateNewFileForm, self).add_prefix(field_name)

    class Meta:
        model = File
        fields = ('category', 'related_degrees', 'file_create_at', 'file_url',)

    def clean_file_url(self):
        file = self.cleaned_data.get('file_url')
        if file:
            filename = file.name
            if filename.split('.')[-1] not in EXTENSIONS_WHITELIST:
                self.add_error('file_url', 'The file extension is not allowed.')
                # raise ValidationError('The file extension is not allowed.')
        return file


class FilterFilesForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Course.objects.all(), required=False)
    degree = forms.ModelChoiceField(queryset=Degree.objects.all(), required=False)
    user = forms.ModelChoiceField(queryset=User.objects.all(), required=False)

    class Meta:
        model = File
        fields = ('category', 'degree', 'user')

files/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from files.forms import CreateNewFileForm, FilterFilesForm
import os
from EasyLearn.settings import MEDIA_ROOT
from files.models import File


@login_required
def show_files(request):
    files = File.objects.all()
    form = FilterFilesForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            category_filter = form.cleaned_data.get('category')
            degree_filter = form.cleaned_data.get('degree')
            user_filter = form.cleaned_data.get('user')
            if category_filter:
                if degree_filter:
                    if user_filter:
                        files = File.objects.filter(category=category_filter, related_degrees=degree_filter, owner=user_filter)
                    else:
                        files = File.objects.filter(category=category_filter, related_degrees=degree_filter)
                elif user_filter:
                    files = File.objects.filter(category=category_filter, owner=user_filter)
                else:
                    files = File.objects.filter(category=category_filter)
            elif degree_filter:
                if user_filter:
                    files = File.objects.filter(related_degrees=degree_filter, owner=user_filter)
                else:
                    files = File.objects.filter(related_degrees=degree_filter)
            elif user_filter:
                files = File.objects.filter(owner=user_filter)
            else:
                files = File.objects.all()

    args = {'files': files, 'form': form}
    return render(request, 'files/show_files.html', args)


@login_required
def add_new_file(request):
    if request.method == 'POST':
        form = CreateNewFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = form.save(commit=False)
            file.owner = request.user
            file.save()
            form.save_m2m()
            return redirect('files:show_files')
    else:
        form = CreateNewFileForm
    return render(request, 'files/new_file.html', {"form": form})


@login_required
def download_file(request, file_id):
    file = File.objects.get(id=file_id)
    args = {'file': file, }
    return render(request, 'files/download_file.html', args)


@login_required
def delete_files(request):
    list_of_files = File.objects.filter(owner=request.user)
    if len(list_of_files) == 0:
        list_of_files = None
    return render(request, 'files/delete_files.html', {'files': list_of_files})


@login_required
def delete_one_file(request, file_id):
    try:
        file = File.objects.get(id=file_id)
        file_path = '{0}/{1}'.format(MEDIA_ROOT, file.file_url)
        os.remove(file_path)
        file.delete()
    except (FileNotFoundError, File.DoesNotExist) as e:
        print(e)
    return delete_files(request)

files/templates/files/delete_files.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if not files %}
        <div class="alert alert-info">
            <strong>Oops!</strong> It looks like you have not uploaded any files.
            <br/>
            You can share your knowledge <a href="{% url 'files:add_file' %}">here</a>
        </div>
    {%else%}
        <div class="content-section">
                <fieldset class="form-group mw-25">
                    <legend class="border-bottom mb-4">List of Your Files</legend>
                            <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col"></th>
                                            <th scope="col">File Name</th>
                                            <th scope="col">Uploaded At</th>
                                        </tr>
                                      </thead>
                                    <tbody>
                                            {% for file in files %}
                                                <tr>
                                                    <td><a href="{% url 'files:delete_one_file' file.id %}" class="btn">delete</a></td>
                                                    <td>{{ file.file_name }}</td>
                                                    <td>{{ file.upload_at.date }}</td>
                                                </tr>
                                            {% endfor %}
                                    </tbody>
                            </table>
                </fieldset>
        </div>
    {%endif%}
{% endblock content %}

files/templates/files/download_file.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
            <fieldset class="form-group mw-25">
                <legend class="border-bottom mb-4">File Details</legend>
                {% if file %}
                    <table class="table table-borderless">
                        <tr>
                            <td><h5>File name:</h5></td>
                            <td>{{ file.file_name }}</td>
                        </tr>
                        <tr>
                            <td><h5>Category:</h5></td>
                            <td>{{ file.category }}</td>
                        </tr>
                        <tr>
                            <td><h5>Related degrees:</h5></td>
                            <td>{{ file.get_str_of_related_degrees }}</td>
                        </tr>
                        <tr>
                            <td><h5>Uploaded by:</h5></td>
                            <td><a class="mr-2" href="/user/show-users/selected-user/{{ file.owner.id }}">{{ file.owner }}</a></td>
                        </tr>
                        <tr>
                            <td><h5>Created at:</h5></td>
                            <td>{{ file.create_at }}</td>
                        </tr>
                        <tr>
                            <td><h5>File size:</h5></td>
                            <td>{{ file.file_size }}</td>
                        </tr>
                        <tr>
                            <td><h5>Uploaded at:</h5></td>
                            <td>{{ file.upload_at }}</td>
                        </tr>
                    </table>
                    <a href="{{ file.file_url.url }}" target="_blank" class="glyphicon-download-alt">Download file</a>
                {% endif %}
            </fieldset>
    </div>
{% endblock content %}

files/templates/files/layout.html
{% extends 'posts/base.html' %}

{% load staticfiles %}
{% block content1 %}

<html lang="en">
	<head>
		<title>{% block title %} {% endblock %} | DatFiles</title>

		<!-- BEGIN META -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="keywords" content="your,keywords">
		<meta name="description" content="Short explanation about this website">
		<!-- END META -->

		<!-- BEGIN STYLESHEETS -->
		<link href='http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900' rel='stylesheet' type='text/css'/>
		<link type="text/css" rel="stylesheet" href="{% static 'css/materialadmin.css' %}" />
		<link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
		<link type="text/css" rel="stylesheet" href="{% static 'css/material-design-iconic-font.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/libs/DataTables/jquery.dataTables.css' %}" />
		<link type="text/css" rel="stylesheet" href="{% static 'css/libs/DataTables/extensions/dataTables.colVis.css' %}" />
		<link type="text/css" rel="stylesheet" href="{% static 'css/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/print.css' %}" />
		<!-- END STYLESHEETS -->

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script type="text/javascript" src="../../assets/js/libs/utils/html5shiv.js?1403934957"></script>
		<script type="text/javascript" src="../../assets/js/libs/utils/respond.min.js?1403934956"></script>
		<![endif]-->
	</head>
	<body class="menubar-pin menubar-hoverable header-fixed "> <!--max sidemenu: menubar-pin -->

		<!-- BEGIN BASE-->
		<div class="col-md-12">

			<!-- BEGIN CONTENT-->
                {% block body %} {% endblock %}
			<!-- END CONTENT -->

		</div><!--end #base-->
		<!-- END BASE -->

		<!-- BEGIN JAVASCRIPT -->
		<script src="{% static 'js/libs/jquery/jquery-1.11.2.min.js' %}"></script>
		<script src="{% static 'js/libs/jquery/jquery-migrate-1.2.1.min.js' %}"></script>
		<script src="{% static 'js/libs/bootstrap/bootstrap.min.js' %}"></script>

		<script src="{% static 'js/libs/nanoscroller/jquery.nanoscroller.min.js' %}"></script>

        <!-- DATATABLE -->
		<script src="{% static 'js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
		<script src="{% static 'js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
		<script src="{% static 'js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>

		<script src="{% static 'js/core/App.js' %}"></script>
		<script src="{% static 'js/core/AppNavigation.js' %}"></script>
		<script src="{% static 'js/core/AppOffcanvas.js' %}"></script>
		<script src="{% static 'js/core/AppCard.js' %}"></script>
		<script src="{% static 'js/core/AppForm.js' %}"></script>
		<script src="{% static 'js/core/AppVendor.js' %}"></script>
		<script src="{% static 'js/core/Demo.js' %}"></script>
        <script src="{% static 'js/core/DemoTableDynamic.js' %}"></script>
		<!-- END JAVASCRIPT -->

	</body>
</html>
{% endblock %}

files/templates/files/new_file.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <title>file</title>
    <form method="POST" enctype="multipart/form-data">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <p class="alert alert-danger"> {{ error }} </p>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-outline-info" type="submit" value="Submit" />
    </form>
</div>
{% endblock content %}

files/templates/files/show_files.html
{% extends 'files/layout.html' %}
{% load crispy_forms_tags %}
{% block title %} All Files {% endblock %}
{% block body %}
<main role="main" class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="col-md-11">
            <table  class="table order-column hover">
             <thead>
                 <tr>
                     <th>{{ form.category|as_crispy_field }}</th>
                     <th>{{ form.degree|as_crispy_field }}</th>
                     <th>{{ form.user|as_crispy_field }}</th>
                     <th>
                        <div class="form-group">
                            <button class="btn btn-outline-info" type="submit">filter</button>
                        </div>
                     </th>
                        <th>
                            <div>
                                <a class="btn btn-outline-info" href="{% url 'files:add_file' %}">Add File</a>
                            </div>
                        </th>
                     <th>
                         <div>
                                <a href="{% url 'files:delete_files' %}" class="btn btn-danger">Delete Files</a>
                         </div>
                     </th>
                 </tr>
             </thead>
            </table>
        </div>
    </form>
</main>
                <section>
                    <div class="section-body" >
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary" style="background-color:#6e8ba0" >
                                        <header>Files Data</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table id="datatable1" class="table order-column hover">
                                                <thead>
                                                    <tr>
                                                        <th>Name</th>
                                                        <th>Category</th>
                                                        <th>Owner</th>
                                                        <th>Create date</th>
                                                        <th>Upload Date</th>
                                                        <th>Size</th>
                                                        <th width="150px">Buttons</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for file in files %}
                                                        <tr class="gradeX">
                                                            <td>{{ file.file_name }}</td>
                                                            <td>{{ file.category }}</td>
                                                            <td>{{ file.owner }}</td>
                                                            <td>{{ file.create_at }}</td>
                                                            <td>{{ file.upload_at }}</td>
                                                            <td>{{ file.file_size }}</td>
                                                            <td>
                                                                <a href="{% url 'files:download_file' file.id %}" class="btn btn-outline-secondary btn-sm">Download</a>
                                                            </td>
                                                        </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        </div><!--end .table-responsive -->
                                    </div>
                                </div>
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>
{% endblock %}