EasyLearn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from users import views as users_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', users_views.home_page, name='home'),  # TODO: move home view to main app
    path('register/', users_views.RegisterFormWizard.as_view(), name='register-wizard'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('user/', include(('users.urls', 'users'), namespace='users')),
    path('post/', include(('posts.urls', 'posts'), namespace='posts')),
    path('file/', include(('files.urls', 'files'), namespace='files')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from chat.views import *

urlpatterns = [
    url(r'^$', RedirectView.as_view(permanent=True, url='inbox/'), name='messages_redirect'),
    url(r'^inbox/$', inbox, name='messages_inbox'),
    url(r'^outbox/$', outbox, name='messages_outbox'),
    url(r'^compose/$', compose, name='messages_compose'),
    url(r'^admin_message/$', compose_admin_message, name='messages_admin_compose'),
    #url(r'^compose/(?P<id>[\d]+)/$', compose, name='messages_compose'),
    url(r'^compose/(?P<recipient>[\w.@+-]+)/$', compose, name='messages_compose_to'),
    url(r'^reply/(?P<message_id>[\d]+)/$', reply, name='messages_reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', view, name='messages_detail'),
    url(r'^delete_inbox/(?P<message_id>[\d]+)/$', delete_inbox, name='message_delete_inbox'),
    url(r'^delete_outbox/(?P<message_id>[\d]+)/$', delete_outbox, name='message_delete_outbox'),
    #url(r'^undelete/(?P<message_id>[\d]+)/$', undelete, name='messages_undelete'),
    #url(r'^trash/$', trash, name='messages_trash'),
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/edit/personal-info/', views.edit_personal_info, name='edit_personal_info'),
    path('profile/edit/more-info/', views.edit_more_info, name='edit_more_info'),
    path('profile/edit/educational-info/', views.edit_educational_info, name='edit_educational_info'),

    path('profile/edit/privacy', views.edit_privacy, name='edit_privacy'),
    path('profile/edit/change-password/', views.change_password, name='change_password'),
    path('show-users/', views.show_users, name='show_users'),
    #path('show-users/selected-user/', views.show_selected_user, name='selected_user'),
    url(r'^show-users/selected-user/(?P<id>[\w-]+)/$', views.show_selected_user, name='selected_user'),
    #url(r'^(?P<slug>[\w-]+)/$', views.show_selected_user),
    path('show-users/results/', views.search_result, name='search'),
    url(r'^friend-request/send/(?P<id>[\w-]+)/$', views.send_friend_request, name='send_friend_request'),
    url(r'^friend-request/cancel/(?P<id>[\w-]+)/$', views.cancel_friend_request,name='cancel_friend_request'),
    url(r'^friend-request/accept/(?P<id>[\w-]+)/$', views.accept_friend_request, name='accept_friend_request'),
    url(r'^friend-request/delete/(?P<id>[\w-]+)/$', views.delete_friend_request, name='delete_friend_request'),
    path('friends/<int:user_id>', views.list_of_friends, name='list_of_friends'),
    path('show-users/delete-user/<int:user_id>', views.delete_friend, name='delete_friend'),

    path('rules/', views.web_rules, name='rules'),
]

users/views.py
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import UserRegisterForm, NewUserProfileForm, NewUserDegreeForm, NewUserCourseForm, ProfileForm
from formtools.wizard.views import SessionWizardView
from .models import Profile, Privacy, FriendRequest, Rules, UserCourses, UserDegrees
from django.urls import reverse
from django.contrib.auth import authenticate, update_session_auth_hash, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.db.models import Q
import os
from EasyLearn.settings import MEDIA_ROOT
from .forms import (
    EditProfileForm,
    PasswordAuthenticationForm,
    EditPersonalInfoForm,
    EditMoreInfoForm,
    ExtraProfileForm,
    EditPrivacyForm,
    EditUserDegreeForm,
    EditUserCourseForm
)
from django.core.paginator import Paginator

User = get_user_model()


TEMP_PICTURES_FOLDER = 'temp_pictures'


class RegisterFormWizard(SessionWizardView):
    template_name = "users/register_wizard.html"
    form_list = [UserRegisterForm, NewUserProfileForm, NewUserDegreeForm, NewUserCourseForm]
    file_storage = FileSystemStorage(location=os.path.join(MEDIA_ROOT, TEMP_PICTURES_FOLDER))

    def get(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            messages.warning(request, f'You already signed in!')
            return home_page(request)
        return super(RegisterFormWizard, self).get(request, *args, **kwargs)

    def done(self, form_list, **kwargs):
        forms_dict = {}
        for form in form_list:
            forms_dict[type(form)] = form

        user_saved = False
        profile_saved = False
        degree_saved = False
        courses_saved = False
        privacy_saved = False

        try:
            user = forms_dict[UserRegisterForm].save(commit=False)
            user.username = str(user.username).lower()
            user.save()
            user_saved = True

            profile = forms_dict[NewUserProfileForm].save(commit=False)
            profile.user = user
            profile.save()
            profile_saved = True

            user_degree = forms_dict[NewUserDegreeForm].save(commit=False)
            user_degree.user_id = profile
            form_degree = forms_dict[NewUserDegreeForm].cleaned_data.get('degree')
            user_degree.degree_id = form_degree
            user_degree.save()
            degree_saved = True

            user_course = forms_dict[NewUserCourseForm].save(commit=False)
            user_course.user_id = profile
            form_courses = forms_dict[NewUserCourseForm].cleaned_data.get('course')
            user_course.save()
            user_course.course_id.set(form_courses)
            forms_dict[NewUserCourseForm].save_m2m()
            courses_saved = True
            privacy = Privacy()
            privacy.user = user
            privacy.save()
            privacy_saved = True

            messages.success(self.request, f'Registration successful!')
            return redirect(reverse('home'))
        except Exception as e:
            print(e)
            if privacy_saved:
                privacy.delete()
            if courses_saved:
                user_course.delete()
            if degree_saved:
                user_degree.delete()
            if profile_saved:
                profile.delete()
            if user_saved:
                user.delete()
            messages.error(self.request, e)
            return home_page(self.request)


def home_page(request):
    return render(request, 'users/home.html')


@login_required
def view_profile(request):
    user_obj = request.user
    profile_obj = Profile.objects.get(user=user_obj)
    user_courses = ()
    try:
        user_courses = tuple(course.course_name for course in tuple([c.course_id.all() for c in
                                                                     UserCourses.objects.filter(user_id=profile_obj)][
                                                                        0]))
    except IndexError as e:
        print(e)
    str_of_courses = ''
    for c in user_courses:
        str_of_courses += '{0}, '.format(str(c))
    if len(str_of_courses) > 0:
        str_of_courses = str_of_courses[:-2]
    user_degree = UserDegrees.objects.get(user_id=profile_obj)
    friend_requests_obj = FriendRequest.objects.filter(to_user=request.user)
    args = {'user': user_obj,
            'profile': profile_obj,
            'friend_requests': friend_requests_obj,
            'user_degree': user_degree,
            'user_courses': str_of_courses

            }
    return render(request, 'users/profile.html', args)


@login_required
def edit_personal_info(request):
    profile_obj = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        u_form = EditPersonalInfoForm(request.POST, instance=profile_obj)
        p_form = EditProfileForm(request.POST, instance=request.user)
        chk_pass = PasswordAuthenticationForm(request, data=request.POST)
        if u_form.is_valid() and p_form.is_valid():
            if chk_pass.is_valid():
                username = chk_pass.cleaned_data.get('username')
                password = chk_pass.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                if user is not None:
                    p_form.save()
                    u_form.save()

                    messages.success(request, f'Your account has been updated!')
                    return redirect(reverse('users:view_profile'))
            else:
                messages.error(request, f'Invalid password!')
        else:
            messages.error(request, f'Invalid fields, your account has not been updated!')

    else:
        u_form = EditPersonalInfoForm(instance=profile_obj)
        p_form = EditProfileForm(instance=request.user)
        chk_pass = PasswordAuthenticationForm()
    context = {
        'u_form': u_form,
        'p_form': p_form,
        'chk_pass': chk_pass
    }

    return render(request, 'users/edit_personal_info.html', context)


@login_required
def edit_more_info(request):
    profile_obj = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = EditMoreInfoForm(request.POST,request.FILES, instance=profile_obj)

        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:view_profile')
        else:
            messages.error(request, f'Invalid fields, your account has not been updated!')
            messages.error(request, form.errors)

    else:
        form = EditMoreInfoForm(instance=profile_obj)
    context = {
        'form': form,
    }
    return render(request, 'users/edit_more_info.html', context)


@login_required
def edit_educational_info(request):
    profile_obj = Profile.objects.get(user=request.user)
    user_course = UserCourses.objects.get(user_id=profile_obj)
    user_degree = UserDegrees.objects.get(user_id=profile_obj)
    if request.method == 'POST':
        courseForm = EditUserCourseForm(data=request.POST, instance=user_course)
        degreeForm = EditUserDegreeForm(data=request.POST, instance=user_degree)
        if courseForm.is_valid() and degreeForm.is_valid():
            degree = degreeForm.cleaned_data.get('degree')
            user_degree.degree_id = degree
            user_degree.save()

            courses = tuple(courseForm.cleaned_data.get('course'))
            UserCourses.objects.get(user_id=profile_obj).delete()
            new_courses = UserCourses(user_id=profile_obj)
            new_courses.save()
            for c in courses:
                new_courses.course_id.add(c)
            new_courses.save()
            # courseForm.save()
            # degreeForm.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:view_profile')
        else:
            messages.error(request, f'Invalid fields, your account has not been updated!')
            messages.error(request, courseForm.errors)
            messages.error(request, degreeForm.errors)
    else:
        courseForm = EditUserCourseForm(instance=user_course)
        degreeForm = EditUserDegreeForm(instance=user_degree)
    context = {
        'c_form': courseForm, 'd_form': degreeForm
    }
    return render(request, 'users/edit_educational_info.html', context)


@login_required
def edit_profile(request):
    messages.info(request, 'what would you like to edit?')
    return render(request, 'users/edit_profile.html')


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, f'Password has been updated for {form.user}!')
            return redirect(reverse('users:view_profile'))
        else:
            messages.error(request, f'Password has not been updated for {form.user}!')
            return redirect(reverse('users:change_password'))

    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'users/change_password.html', args)


@login_required
def show_users(request):
    users = User.objects.all()
    args = {'users': users}
    return render(request, 'users/search_users.html', args)


@login_required
def show_selected_user(request, id):
    try:
        if request.user.id == int(id):
            return view_profile(request)
    except ValueError as e:
        print(e)

    user = get_object_or_404(User, id=id)

    profile_obj = Profile.objects.get(user=user)

users/templates/users/change_password.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Change Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/edit_educational_info.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Educational Info</legend>
                {{ c_form|crispy }}
                {{ d_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/edit_more_info.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">More Info</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">submit</button>
            </div>
        </form>
    </div>

<script>
document.getElementById("profile_pic-clear_id").style.display = "none";
</script>

{% endblock content %}

users/templates/users/edit_personal_info.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group mw-25">
                <legend class="border-bottom mb-4">Personal Info</legend>
                <div id="myModal"  class="modal  content-section">
                    <div class="col-md-3 panel panel-default " style="border-radius:18px;">
                    <form method="POST">
                        <div  class="h-100 row align-items-center">
                            <a class="bg-danger text-white" aria-label="Close" id="cols" >close</a></br></br>
                {{ chk_pass|crispy }}
                        </br>
             <button class="btn btn-outline-info" id="submit" type="submit">submit</button>

                            </div>
                    </form>
                </div>
                </div>
                {{ p_form|crispy }}
                {{ u_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" id="myBtn">submit</button>
            </div>
        </form>
    </div>
<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementById("cols");

// When the user clicks the button, open the modal
btn.onclick = function() {
  modal.style.display = "block";
document.getElementById('div_id_username').style.display = "none";
document.getElementById('id_username').value = "{{user}}"
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}



</script>

<style>
body {font-family: Arial, Helvetica, sans-serif;}

.panel{

  position: fixed; /* Stay in place */
  z-index: 0; /* Sit on top */
  padding-top: -200px; /* Location of the box */
  padding-left:-20px;
  width: 200px; /* Full width */
  height: 200px; /* Full height */
  margin:50px;
  background-color: rgba(1,25,100,0.5); /* Black w/ opacity */
}
/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  padding-left:600px;
  left: 5;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
  position: relative;
  background-color: #fefefe;
  margin: auto;
  padding: 0;
  border: 1px solid #888;
  width: 80%;
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
}

.modal-header {
  padding: 2px 16px;
  background-color: #5cb85c;
  color: white;
}

.modal-body {padding: 2px 16px;}

.modal-footer {
  padding: 2px 16px;
  background-color: #5cb85c;
  color: white;
}
</style>
{% endblock content %}

users/templates/users/edit_privacy.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Privacy</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/edit_profile.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
            <fieldset class="form-group mw-25">
                <legend class="border-bottom mb-4">Edit Profile</legend>
                <a href="{% url 'users:edit_personal_info' %}" class="btn btn-default">Personal Info</a><br><br>
                <a href="{% url 'users:edit_more_info' %}" class="btn btn-default">More Info</a><br><br>
                <a href="{% url 'users:edit_educational_info' %}" class="btn btn-default">Educational Info</a><br><br>
                <a href="{% url 'users:change_password' %}" class="btn btn-default" >Change Password</a><br><br>
                <a href="{% url 'users:edit_privacy' %}" class="btn btn-default" >Privacy</a>

            </fieldset>

    </div>
{% endblock content %}

users/templates/users/home.html
{% extends "posts/base.html" %}
{% block content %}
<style>
    body  {
      background: url("https://images.unsplash.com/photo-1434030216411-0b793f4b4173?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80") center center fixed;
      opacity: 0.7;
      background-size: cover
    }
</style>
    {# Hero Section #}
    <div class="mkt-s1">
        <div class="mkt-s1-body container ">
            <div>
                <br/>
            </div>
            <div>
                <img src="https://www.swissmadesoftware.org/.imaging/w500-png/dam/6b2c61f7-42a3-401e-bb3d-506ff0797d16/easylearn-Logo-RGB.png" alt="" style="width:23%">
            </div>
            <div>
            </div>
            <div class="row">
                <h1 class="col-md-8" style="color:black">Welcome to Easy Learn -</h1>
                <h3 class="col-md-8" style="color:black">Educational Social Network</h3>
            </div>
            <br/>
            <div class="row">
                <p class="col-md-8" style="color:black">Easy learn is a social network that designed to facilitate the sharing of
            educational material between students from all educational institutions.</p>
            </div>
            <div class="row">
            </div>
        </div>
    </div>
{% endblock content %}

{% block sidebar %}
    {% if user.is_authenticated %}
    {% else %}
        <br/>
        <br/>
        <div>
            <h3 style="color:black">Create a new account</h3>
            <p style="color:black">It's free and always will be.</p>
            <br/>
            <br/>
            <font style="color:black" size="1">By clicking Sign Up, you agree to our Terms and Data Policy.</font>
            <a href="{% url 'register-wizard' %}"
               class="sign-up btn btn-success">Sign Up Now!
            </a>
        </div>
        <div>
            <br/>
            <hr style="height:1px;border:none;color:#333;background-color:#333;">
            <br/>
            <br/>
            <br/>
        </div>
        <div>
            <h3 style="color:black">You have an already account?</h3>
            <br/>
            <a href="{% url 'login' %}"
               class="sign-in btn btn-success">Sign In
            </a>
        </div>
    {% endif %}
{% endblock %}

users/templates/users/list_of_friends.html
{% extends "posts/base.html" %}
{% block navbar %}
    <a class='btn btn-primary' onclick="window.close()">Close</a>
    <br/><br/>
    <h4> Friends list of {{ user.first_name }} {{ user.last_name }} </h4>
{% endblock navbar %}


{% block content %}
    {% for friend in friends_list %}
        <a class='btn btn-link' onclick="close_and_redirect_parent('/user/show-users/selected-user/{{ friend.user.id }}')">
            {{ friend.user.first_name }} {{ friend.user.last_name }}
        </a>
        <br><br>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if friends_list.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">&laquo; first</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ friends_list.previous_page_number }}">previous</a>
            {% endif %}

            {% for num in friends_list.paginator.page_range %}
                {% if friends_list.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > friends_list.number|add:'-3' and num < friends_list.number|add:'3' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if friends_list.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ friends_list.next_page_number }}">next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ friends_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    <div>
        Page {{ friends_list.number }} of {{ friends_list.paginator.num_pages }}
    </div>

    <script language="javascript" type="text/javascript">
        function close_and_redirect_parent(url) {
            window.opener.location.href = url;
            window.close();
        }
    </script>

{% endblock content %}

users/templates/users/login.html
{% extends "posts/base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="content-section">
    <div class="container">
    <title>login</title>
        <form method="POST">
            <h2>Please Login</h2>
            {% csrf_token %}
            {{ form|crispy }}
            <br><button class="btn btn-outline-info" type="submit">Login</button>
        </form>
        </div>
</div>

{% endblock content %}

users/templates/users/profile.html
{% extends "posts/base.html" %}
{% block head %}
<title>Profile</title>
<style>
        .imageProfile {
        border: 1px solid black;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="content-section">

   <div class="imageProfile">
       {% if profile.profile_pic %}
            <img src={{ profile.profile_pic.url }} alt="Paris" style="width:13%">
        {% else %}
            <img src="https://i.stack.imgur.com/l60Hf.png" alt="Paris" style="width:13%">
       {% endif %}

    </div>
<div class="container">
    <div class="well">
    <legend class="border-bottom mb-4">Profile        <a href="{% url 'users:edit_profile' %}" class="btn btn-default" >edit</a>
</legend>
        <p>Username: {{ user }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>gender: {{ profile.gender }}</p>
        <p>birth date: {{ profile.birth_date }}</p>
        <p>college name: {{ profile.college_name }}</p>
        <p>year of study: {{ profile.year_of_study }}</p>
        <p>about me: {{ profile.about_me }}</p>
        <p>degree: {{ user_degree.degree_id }}</p>
        <p>courses: {{ user_courses }}</p>
    </div>
</div>

<div class="container">
</div>
</div>

<!--</div>-->
    <!--{% if user.userprofile.image %}-->
    <!--{% endif %}-->
<!--</div>-->

{% endblock content %}

{% block sidebar %}
{% for r_request in friend_requests %}
    <div class="content-section">

			<p>You have request from <a href="/user/show-users/selected-user/{{ r_request.from_user.id }}">{{ r_request.from_user.username }}</a></p>
            <small><a class='btn btn-primary' href="/user/friend-request/accept/{{ r_request.from_user.id }}">Accept</a></small>
			<small><a class='btn btn-warning' href="/user/friend-request/delete/{{ r_request.from_user.id }}">Ignore</a></small>
            </div>

		{% endfor %}
{% endblock %}

users/templates/users/search_users.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="GET" action="{% url 'users:search' %}">
        <p><input name="q" value="{{request.GET.q}}" placeholder="search.."/><span style="margin-left: 10px; position: absolute;">
            <button class="btn btn-outline-info btn-sm" type="submit">Search</button></span></p>
        <hr>
    </form>
    {% for u in users%}
        {% if u != user%}
            <p><a class='btn btn-default' href="/user/show-users/selected-user/{{ u.id }}">{{u.first_name}} {{u.last_name}}</a></p>
         {% endif %}
        {% endfor %}
</div>
{% endblock content %}

users/templates/users/show_selected_user.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block head %}
<title>Profile</title>
<style>
    .imageProfile {
    border: 1px solid black;
    }
</style>
{% endblock head%}

{% block content %}
    <div class="content-section">
        <div class="imageProfile">
       {% if profile.profile_pic %}
            <img src={{ profile.profile_pic.url }} alt="Paris" style="width:13%">
        {% else %}
            <img src="https://i.stack.imgur.com/l60Hf.png" alt="Paris" style="width:13%">
       {% endif %}
        </div>
        <div class="container">
            <div class="well">
                <legend class="border-bottom mb-4">Profile</legend>
                <p>Username: {{ user }}</p>
                {% if button_status == 'friends' %}
                    {% for field in profile_form %}
                        {{ field.label }}: {{ field.value }}<br><br>
                    {% endfor %}
                    {% for field in extra_form %}
                        {{ field.label }}: {{ field.value }}<br><br>
                    {% endfor %}
                {% else %}
                    <p>First name: {{ user.first_name }}</p>
                    <p>Last name: {{ user.last_name }}</p>
                {% endif %}
            </div>
        </div>
    </div>

    <!--</div>-->
        <!--{% if user.userprofile.image %}-->
        <!--{% endif %}-->
    <!--</div>-->

{% endblock content %}

{% block sidebar %}
    <div>
        {% if button_status == 'not_friend' %}
            <small><a class='btn btn-primary' href="/user/friend-request/send/{{ user.id }}">Add Friend</a></small>
        {% elif button_status == 'friend_request_sent' %}
            <small><a class="btn btn-warning" href="/user/friend-request/cancel/{{ user.id }}">Cancel Request</a></small>
        {% elif button_status == 'friends' %}
        <table>
            <tr>
                <th> <small><a class="btn btn-outline-info mb-4" onclick="pop_it_up('{% url 'users:list_of_friends' user.id %}')">Show List of Friends</a></small> </th>
            <tr>
                <th> <small><a class="btn btn-outline-danger mb-4" href="{% url 'users:delete_friend' user.id %}">Remove Friend</a></small> </th>
            </tr>
        </table>
        {% endif %}
    </div>
    <script language="javascript" type="text/javascript">
        function pop_it_up(url) {
            new_window = window.open(url,'{{ title }}', 'height=600, width=400');
            if (window.focus) {new_window.focus()}
        }
    </script>

{% endblock sidebar %}

users/templates/users/test.html
{% extends "base.html" %}
{% block content %}
    <h1>Test</h1>
{% endblock content %}