EasyLearn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from users import views as users_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', users_views.home_page, name='home'),  # TODO: move home view to main app
    path('register/', users_views.RegisterFormWizard.as_view(), name='register-wizard'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('user/', include(('users.urls', 'users'), namespace='users')),
    path('post/', include(('posts.urls', 'posts'), namespace='posts')),
    path('file/', include(('files.urls', 'files'), namespace='files')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from chat.views import *

urlpatterns = [
    url(r'^$', RedirectView.as_view(permanent=True, url='inbox/'), name='messages_redirect'),
    url(r'^inbox/$', inbox, name='messages_inbox'),
    url(r'^outbox/$', outbox, name='messages_outbox'),
    url(r'^compose/$', compose, name='messages_compose'),
    url(r'^admin_message/$', compose_admin_message, name='messages_admin_compose'),
    #url(r'^compose/(?P<id>[\d]+)/$', compose, name='messages_compose'),
    url(r'^compose/(?P<recipient>[\w.@+-]+)/$', compose, name='messages_compose_to'),
    url(r'^reply/(?P<message_id>[\d]+)/$', reply, name='messages_reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', view, name='messages_detail'),
    url(r'^delete_inbox/(?P<message_id>[\d]+)/$', delete_inbox, name='message_delete_inbox'),
    url(r'^delete_outbox/(?P<message_id>[\d]+)/$', delete_outbox, name='message_delete_outbox'),
    #url(r'^undelete/(?P<message_id>[\d]+)/$', undelete, name='messages_undelete'),
    #url(r'^trash/$', trash, name='messages_trash'),
]

files/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

urlpatterns = [
    path('show-files/', views.show_files, name='show_files'),
    path('add-file/', views.add_new_file, name='add_file'),
    path('download-file/', views.download_file, name='download_file'),
    url(r'^download-file/(?P<file_id>\d+)/$', views.download_file, name='download_file'),
    path('delete-files/', views.delete_files, name='delete_files'),
    path('delete/<int:file_id>/', login_required(views.delete_one_file), name='delete_one_file'),
]

posts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.conf.urls import url
from . import views
from .views import PostListView, PostDetailView

urlpatterns = [
    path('show_post/<int:pk>/', login_required(PostDetailView.as_view()), name='post-detail'),
    path('feed/', login_required(PostListView.as_view()), name='feed'),
    path('new/', views.create_new_post, name='newPost'),
    url(r'^delete_post/(?P<post_id>\d+)/$', views.delete_post, name='delete_post'),
    path('delete-comment/<int:comment_id>', login_required(views.delete_comment), name='delete_comment'),
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/edit/personal-info/', views.edit_personal_info, name='edit_personal_info'),
    path('profile/edit/more-info/', views.edit_more_info, name='edit_more_info'),
    path('profile/edit/educational-info/', views.edit_educational_info, name='edit_educational_info'),

    path('profile/edit/privacy', views.edit_privacy, name='edit_privacy'),
    path('profile/edit/change-password/', views.change_password, name='change_password'),
    path('show-users/', views.show_users, name='show_users'),
    #path('show-users/selected-user/', views.show_selected_user, name='selected_user'),
    url(r'^show-users/selected-user/(?P<id>[\w-]+)/$', views.show_selected_user, name='selected_user'),
    #url(r'^(?P<slug>[\w-]+)/$', views.show_selected_user),
    path('show-users/results/', views.search_result, name='search'),
    url(r'^friend-request/send/(?P<id>[\w-]+)/$', views.send_friend_request, name='send_friend_request'),
    url(r'^friend-request/cancel/(?P<id>[\w-]+)/$', views.cancel_friend_request,name='cancel_friend_request'),
    url(r'^friend-request/accept/(?P<id>[\w-]+)/$', views.accept_friend_request, name='accept_friend_request'),
    url(r'^friend-request/delete/(?P<id>[\w-]+)/$', views.delete_friend_request, name='delete_friend_request'),
    path('friends/<int:user_id>', views.list_of_friends, name='list_of_friends'),
    path('show-users/delete-user/<int:user_id>', views.delete_friend, name='delete_friend'),

    path('rules/', views.web_rules, name='rules'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from files.models import File


class Post(models.Model):
    category = models.CharField(max_length=50)
    body = models.TextField(max_length=5000)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    file = models.OneToOneField(File, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.category


class Comments(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=250)
    postId = models.ForeignKey(Post, on_delete=models.CASCADE)
    publish_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{0}-{1}'.format(self.postId.category, str(self.author.username))

posts/forms.py
from django import forms
from posts.models import Post, Comments
from users.models import Course

PRIVATE_CATEGORY = 'private'
FIELD_NAME_MAPPING = {
    'category': 'post_type'
}


class NewPostForm(forms.ModelForm):
    CATEGORY_CHOICES = (
        (PRIVATE_CATEGORY, 'private'),
    )
    COURSES = ()
    try:
        COURSES = tuple(map(lambda course_name: (course_name, course_name), Course.objects.only('course_name')))
    except Exception as e:
        print(e)
    category_list = CATEGORY_CHOICES + COURSES
    category_rules = 'By selecting the "Other" option, only your friends can view the post. ' \
                     'Otherwise the post will be set to public.'

    category = forms.ChoiceField(help_text=category_rules, choices=category_list)
    body = forms.CharField(max_length=5000, widget=forms.Textarea)

    def add_prefix(self, field_name):
        # look up field name; return original if not found
        field_name = FIELD_NAME_MAPPING.get(field_name, field_name)
        return super(NewPostForm, self).add_prefix(field_name)

    class Meta:
        model = Post
        fields = ('category', 'body',)


class Comment(forms.ModelForm):
    comment = forms.CharField(max_length=250,
                              widget=forms.TextInput(attrs={'placeholder': 'write comment...'}),
                              help_text='Please write your comment (maximum 250 characters)')

    class Meta:
        model = Comments
        fields = ('comment', )

posts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Post, Comments
from django.views.generic import ListView, DetailView
from .forms import NewPostForm, Comment, PRIVATE_CATEGORY
from users.models import Profile, UserCourses
from files.forms import CreateNewFileForm

FLAGS = {
    'want_add_file': False
}


class PostListView(ListView):
    model = Post
    template_name = 'posts/Feed.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date']
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        posts_list = self.get_queryset()
        posts = []
        for post in posts_list:
            profile = Profile.objects.get(user=post.author)
            p = {'post': post, 'profile': profile}
            posts.append(p)
        context.update({
            'all_posts': posts,
        })
        return context

    def get_queryset(self):
        profile_obj = Profile.objects.get(user=self.request.user)
        friends_list = tuple(friend.user.username for friend in profile_obj.friends.all())
        all_posts = Post.objects.all().order_by('-date')
        user_courses = ()
        try:
            user_courses = tuple(course.course_name for course in tuple([c.course_id.all() for c in
                                                                UserCourses.objects.filter(user_id=profile_obj)][0]))
        except IndexError as e:
            print(e)
        posts_to_show = []
        for post in all_posts:
            if post.category == PRIVATE_CATEGORY and post.author.username in (friends_list + (self.request.user.username,)):
                posts_to_show.append(post)
            elif post.category in user_courses:
                posts_to_show.append(post)
        return posts_to_show


class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'
    form_class = Comment

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        comment_form = self.form_class(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.author = self.request.user
            new_comment.postId = self.object
            new_comment.save()
            self.form_class = Comment
        else:
            messages.error(request, f'Some error occurred while posting your comment.')
            self.form_class = comment_form
        context = self.get_context_data()
        return super(PostDetailView, self).render_to_response(context)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data()
        return super(PostDetailView, self).render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['comments'] = Comments.objects.filter(postId_id=self.object).order_by('-publish_date')
        context['comment_form'] = self.form_class
        return context


@login_required
def create_new_post(request):
    if request.method == 'POST':
        post_form = NewPostForm(request.POST)
        if 'add_file' in request.POST:
            FLAGS['want_add_file'] = True
            file_form = CreateNewFileForm
            return render(request, 'posts/new_post.html', {"post_form": post_form, "file_form": file_form})
        else:
            if post_form.is_valid():
                post = post_form.save(commit=False)
                post.author = request.user
                if FLAGS['want_add_file'] is True:
                    file_form = CreateNewFileForm(request.POST, request.FILES)
                    if file_form.is_valid():
                        file = file_form.save(commit=False)
                        file.owner = request.user
                        file.save()
                        file_form.save_m2m()
                        post.file = file
                        FLAGS['want_add_file'] = False
                    else:
                        error_message = file_form.errors
                        post_form = NewPostForm
                        return render(request, 'posts/new_post.html',
                                      {"post_form": post_form, "error_message": error_message})
                else:
                     post.file = None
                post.save()
                return redirect('posts:feed')
            else:
                error_message = 'Error by trying to write post!'
                post_form = NewPostForm
                return render(request, 'posts/new_post.html', {"post_form": post_form, "error_message": error_message})

    else:
        post_form = NewPostForm
        return render(request, 'posts/new_post.html', {"post_form": post_form})


@login_required
def delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return redirect('posts:feed')


@login_required
def delete_comment(request, comment_id):
    try:
        comment = Comments.objects.get(id=comment_id)
        post_id = comment.postId.id
        if request.user != comment.author:
            messages.error(request, 'You cannot delete comment of other user!')
            return PostDetailView.as_view()(request, pk=post_id)
        comment.delete()
        return PostDetailView.as_view()(request, pk=post_id)
    except Comments.DoesNotExist as e:
        print(e)
        return redirect('posts:feed')

posts/templates/posts/Feed.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <img src="https://www.swissmadesoftware.org/.imaging/w500-png/dam/6b2c61f7-42a3-401e-bb3d-506ff0797d16/easylearn-Logo-RGB.png" alt="" style="width:23%">
    {% for p in all_posts %}
        <article class="content-section" >
           {% if p.profile.profile_pic %}
                <img class="rounded-circle article-img" src="{{ p.profile.profile_pic.url }}">
            {% else %}
                <img class="rounded-circle article-img" src="https://i.stack.imgur.com/l60Hf.png">
           {% endif %}
          <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="/user/show-users/selected-user/{{ p.post.author.id }}">{{ p.post.author }}</a>
              <small class="text-muted">{{ p.post.date|date:"F d, Y" }}</small>
            </div>
            <div>
                <h3><a class="article-title" href="{% url 'posts:post-detail' p.post.id %}">{{ p.post.category }}</a></h3>
                <p class="article-content">{{ p.post.body }}</p>
                {% if p.post.file %}
                    <a class="article-content" href="{% url 'files:download_file' p.post.file.id %}">{{ p.post.file }}</a>
                {% endif %}
            </div>
          </div>
        </article>
    {% endfor %}

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %}

{% block sidebar %}
    <a href="{% url 'posts:newPost' %}" class="btn btn-outline-info">Create Post</a>
{% endblock %}

posts/templates/posts/base.html
{% load static %}
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Easy Learn</title>
    {% endif %}

</head>
<body>
    {% block navbar %}
        <header class="site-header">
          <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'home' %}">Easy Learn</a>
                <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="{% url 'users:rules' %}">Site Rules</a>
                </div>
              <div class="collapse navbar-collapse" id="navbarToggle">

                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                  {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'posts:feed' %}">Feed</a>
                    <a class="nav-item nav-link" href="{% url 'users:view_profile' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'files:show_files' %}">Search Files</a>
                    <a class="nav-item nav-link" href="{% url 'chat:messages_inbox' %}">Messages</a>
                    <a class="nav-item nav-link" href="{% url 'users:search' %}">Find Friends</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                </div>
                  {% else %}
                  {% endif %}
                </div>
              </div>
            </div>
          </nav>
        </header>
    {% endblock navbar %}
    {% block main %}
    {% block content1 %}{% endblock %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
<!--                <div class="content-section">-->
                    {% block sidebar %}{% endblock %}
<!--                </div>-->
            </div>
        </div>
    </main>
    {% endblock main %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

posts/templates/posts/home_posts.html
{% extends "posts/base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="content-section" >
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date|date:"F d, Y" }}</small>
            </div>
            <div>
                <h3>{{ post.category }}</h3>
                <p class="article-content">{{ post.body }}</p>
            </div>
          </div>

        </article>
    {% endfor %}
{% endblock content %}

posts/templates/posts/new_post.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <title>create new post</title>
    <form method="POST"  enctype="multipart/form-data">
        {% if error_message %}
            {% csrf_token %}
            <p style="color:red">{{ error_message }}</p>
        {% endif %}
        {% csrf_token %}
        {{ post_form|crispy }}
        <div>
            <input class="btn btn-link" name="add_file" type="submit" value="add file" />
            {% if file_form %}
                {% csrf_token %}
                {{ file_form|crispy }}
            {% endif %}
        </div>
        <br>
        <div>
            <input class="btn btn-outline-info" name="add_post" type="submit" value="Add Post" />
        </div>
    </form>
</div>

{% endblock content %}

posts/templates/posts/post_detail.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <article class="content-section" >
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="/user/show-users/selected-user/{{ post.author.id }}">{{ post.author }}</a>
          <small class="text-muted">{{ post.date|date:"F d, Y" }}</small>
        </div>
        <div>
            <h3>{{ post.category }}</h3>
            <p class="article-content">{{ post.body }}</p>
        </div>
      </div>
    </article>

    <form method="post">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <input class="btn btn-outline-info mb-4" type="submit" value="Add Comment" />
    </form>

    <div class="main-comment-section">
        {{ comments.count }} Comment{{ comments|pluralize }}
        {% for comment in comments %}
            <blockquote class="blockquote">
                <p class="mb-0">{{ comment.comment }}</p>
                <footer class="blockquote-footer">
                    By <a class="mr-2" href="/user/show-users/selected-user/{{ comment.author.id }}">{{ comment.author|capfirst }}</a>,
                    {{ comment.publish_date|date:"d F Y, h:m" }}
                    {% if user == comment.author %}
                        <a href="{% url 'posts:delete_comment' comment.id %}" class="btn">delete</a>
                    {% endif %}
                </footer>
            </blockquote>
        {% endfor %}
    </div>

{% endblock content %}

{% block sidebar %}
    {% if user == post.author %}
        <a href="{% url 'posts:delete_post' post.id %}" class="btn btn-outline-info">Delete Post</a>
    {% endif %}
{% endblock %}